name = "SkyLLG"
uuid = "00d88b7d-44fe-44d2-9db6-8ed2d3a0fc3c"
authors = ["Felipe Reyes-Osorio"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
